In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr1.shape

(2, 3)

In [9]:
arr = np.zeros([3,2])
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
arr = np.ones([3,2])
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
arr = np.full([5,5],fill_value=5)
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [18]:
arr = np.eye(N=5,M = 5)#diagonal

In [19]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
x = b'l love zoobeezoo'
arr = np.frombuffer(x,dtype = 'S1')
arr

array([b'l', b' ', b'l', b'o', b'v', b'e', b' ', b'z', b'o', b'o', b'b',
       b'e', b'e', b'z', b'o', b'o'], dtype='|S1')

In [24]:
arr = np.linspace(1,10,10)

In [29]:
arr = np.logspace(1,32,7)

In [30]:
arr

array([1.00000000e+01, 1.46779927e+06, 2.15443469e+11, 3.16227766e+16,
       4.64158883e+21, 6.81292069e+26, 1.00000000e+32])

In [34]:
rand = np.random.rand(3,2)

In [35]:
rand

array([[0.86244961, 0.35019773],
       [0.97595496, 0.11213844],
       [0.58020621, 0.41363461]])

In [37]:
rand = np.random.random(3)

In [38]:
rand

array([0.44419045, 0.00637552, 0.26827231])

In [39]:
arr = np.random.randint(1,10,5)

In [40]:
arr

array([9, 9, 4, 1, 7])

In [43]:
arr = np.random.randn(2,4)
arr

array([[-0.80697752, -1.37635606,  1.35643357,  0.55824404],
       [-1.64756984, -0.03880985,  0.6488157 ,  0.73103493]])

In [44]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
print(arr[[0,1,2],[1,1,1]])#配对pair

[2 5 8]


In [48]:
print(arr[0:2,0:2])

[[1 2]
 [4 5]]


In [50]:
print(arr[0:2,[0,1]])#索引辅助

[[1 2]
 [4 5]]
