**项目分析：一元一次方程的线性回归预测**

In [48]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [49]:
X_height = np.array([0,500,1000,1500,2000,2500,3000,3500,4000])
display(y_height.ndim,y_height.shape)

1

(9,)

In [60]:
X_height = X_height.reshape(-1,1)#这里表示9个方程，必须是二维的,注意要接受返回值

In [61]:
y_temp = np.array([12.834044,10.190649,5.500229,2.854665,-0.706488,-4.065323,-7.127480,-10.058879,-13.206465])

In [63]:
model = LinearRegression(fit_intercept=True)
model.fit(X_height,y_temp)
display(model.coef_,model.intercept_)

array([-0.00656953])

12.718507511111111

In [67]:
model = LinearRegression(fit_intercept=False)#他把那个权重很小的数当成正常数看了，也就是不考虑斜率了，函数过原点，我们要让他知道有一组数据，他在每个方程给的权重是一样的，这个就是截距
model.fit(X_height,y_temp)
display(model.coef_,model.intercept_)
#截距在方程中相当于w0*1,我们想算出截距，因为根据我们的观察，当高度为0时，温度存在一个非0值，所以fit必须设置为true，否则算不出这个值

array([-0.00208065])

0.0

In [66]:
np.linalg.inv(X_height.T.dot(X_height)).dot(X_height.T).dot(y_temp)

array([-0.00208065])

**此时求出了一个系数，因为有多少个列向量，就能解出多少个w，和上面的还不一样，之所以上面能求出，我们让算法考虑了截距存在**

In [68]:
#要想用手敲正规方程算出真正的w0，我们要手动增加，这个过程就是fit_intercept=true的内部原理
X_height = np.concatenate([X_height,np.full(shape=(9,1),fill_value=1)],axis = 1)

In [69]:
X_height#增加一列，让正规方程能够算出这个截距
#正规方程是由最小二乘法经求导后取极小值时对应的解

array([[   0,    1],
       [ 500,    1],
       [1000,    1],
       [1500,    1],
       [2000,    1],
       [2500,    1],
       [3000,    1],
       [3500,    1],
       [4000,    1]])

In [71]:
np.set_printoptions(suppress=True)
np.linalg.inv(X_height.T.dot(X_height)).dot(X_height.T).dot(y_temp)
#求出系数，截距，正规方程就是用来求系数w的，这里我们把b拆解为W0*1就是为了在求正规方程的时候能把截距看做是系数，一并求出，这就要求X加多一列“1”
#且sklearn模型要设置为true，机器才知道你要这么干

array([-0.00656953, 12.71850751])

**总结：考虑截距，是一种添加偏置项的方式，我们让线性方程拜托原点的束缚，使其拟合出来的方程更加精确。之所以存在了截距而使得代码要考虑“截距”的情况，是因为我们的方程本来就存在截距，而且在最小二乘法中“预测值-真实值”时，预测值部分是有个“b”的，也就是ax+b，如果不考虑截距，所得到的正规方程当然就只有一个解，也就相当于sklearn模型不考虑截距，算出来的结果当然不是准的。**

**该章节的点睛之笔就是对b截距的拆分+对x的增广，将他看成系数*1（这里的系数就是截距），使其能用正规方程和前面的系数一并求出，让前面的系数更加精确**

**拓展探究：让原数据height=0的方程